# Generated by Django 4.0.5 on 2022-07-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_website', '0003_remove_contest_has_errors_remove_contest_is_fresh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='allow_ghosts',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='is_ghost',
        ),
    ]
