# Generated by Django 4.0.5 on 2022-08-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_website', '0005_alter_contest_options_alter_monitor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='last_big_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='last_ping',
            field=models.DateTimeField(null=True),
        ),
    ]
