# Generated by Django 4.0.5 on 2022-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_website', '0006_contest_last_big_update_contest_last_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='verdict',
            field=models.CharField(max_length=20),
        ),
    ]
