# Generated by Django 4.0.5 on 2022-08-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_website', '0007_alter_submit_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(null=True, verbose_name='Сложность'),
        ),
    ]
