# Generated by Django 4.0.5 on 2022-08-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_website', '0008_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='test_no',
            field=models.IntegerField(null=True),
        ),
    ]
