# Generated by Django 4.0.5 on 2022-08-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_website', '0009_submit_test_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='submit',
            name='max_time',
            field=models.IntegerField(null=True),
        ),
    ]
