# Generated by Django 4.0.5 on 2022-08-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_website', '0012_alter_contest_error_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='last_big_update',
        ),
    ]
