version: '3.8'

services:
  web:
    build: ./src
    command: gunicorn superMonitor.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env.db
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data:
