# Generated by Django 4.0.5 on 2022-08-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterKeyWord',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
