# Generated by Django 4.0.5 on 2022-07-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_website', '0002_remove_monitor_name_alter_personality_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='has_errors',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='is_fresh',
        ),
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('FRESH', 'Только что создан'), ('OK', 'OK'), ('ERROR', 'Ошибка!')], default='FRESH', max_length=10),
        ),
        migrations.AddField(
            model_name='monitor',
            name='default_ghosts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submit',
            name='verdict',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Не зачтено')], max_length=10),
        ),
    ]
